INSERT INTO jokes (body, author_id) VALUES
('Why don''t oysters donate to charity? Because they''re shellfish.', 1),
('What does a baby computer call its father? Data.', 1),
('What did the custodian say when he jumped out of the closet? "Supplies!"', 1),
('Why are colds bad criminals? Because they''re easy to catch.', 1),
('How does a penguin build its house? Igloos it together.', 1),
('Which knight invented King Arthur''s Round Table? Sir Cumference.', 1),
('What do sprinters eat before a race? Nothing. They fast.', 1),
('What do you call a fly without wings? A walk!', 1),
('What happens when you witness a ship wreck? You let it sink in.', 1),
('How can you find Will Smith in the snow? Follow the fresh prints.', 1),
('What does a clock do when it''s hungry? It goes back four seconds.', 1),
('What''s the easiest way to make a glow worm happy? Cut off its tail—it''ll be delighted!', 1),
('What do you call a belt made of watches? A waist of time!', 1),
('Why did Adele cross the road? To say hello from the other side!', 1),
('What''s the best way to carve wood? Whittle by whittle.', 1),
('What did the teacher do with the student''s report on cheese? She grated it.', 1),
('What''s the difference between a piano and a fish? You can tune a piano, but you can''t tuna fish.', 1),
('What did the pirate say on his 80th birthday? "Aye, matey!"', 1),
('How do you organize an astronomer''s party? You planet.', 1),
('What''s the action like at a circus? In-tents.', 1),
('Why did the scarecrow get promoted? Because he was outstanding in his field.', 1),
('Why does Snoop Dogg carry an umbrella? Fo'' drizzle.', 1),
('What do you call a pony with a sore throat? A little hoarse.', 1),
('What do you call a fish with no eye? Fsh.', 1),
('What do you call a boomerang that doesn''t come back? A stick!', 1),
('What kind of car does an egg drive? A Yolkswagen.', 1),
('What do you call a factory that sells generally decent goods? A satisfactory.', 1),
('Why was 6 afraid of 7? Because 7 ate 9.', 1),
('Why should you never eat a clock? Because it''s too time-consuming.', 1),
('What should a sick bird do? Get tweetment.', 1),
('I want a job cleaning mirrors. It''s something I can really see myself doing.', 1),
('What grades did the pirate get on his report card? Seven Cs.', 1),
('How do you make a tissue dance? Put a little boogie in it.', 1),
('How did Ebenezer Scrooge win the football game? The ghost of Christmas passed!', 1),
('Did you hear about the mediocre restaurant on the moon? It has great food but no atmosphere.', 1),
('What kinds of pictures do hermit crabs take? Shellfies.', 1),
('What do you get a man with the heart of a lion? A lifetime ban from the zoo.', 1),
('What do you call a person with a briefcase in a tree? A branch manager.', 1),
('Why did the baby cookie cry? Because its mother was a wafer so long.', 1),
('What''s the difference between an alligator and a crocodile? One you''ll see later, the other you''ll see in a while.', 1),
('When is a door not really a door? When it''s really ajar.', 1),
('What do you do when you see a spaceman? Park in it, man.', 1),
('Why do you never see elephants hiding in trees? Because they''re so good at it!', 1),
('Did you hear about the claustrophobic astronaut? Poor guy really needed some space.', 1),
('What''s the No. 1 cause of divorce? Marriage!', 1),
('Why did the coffee call the police? It got mugged!', 1),
('Why did Cyclops close his school? He only had one pupil.', 1),
('Where do skunks pray? In pews.', 1),
('If you''re American when you come out of the bathroom, what are you when you''re in the bathroom? European.', 1),
('Why do birds fly south for the winter? Because it''s too far to walk.', 1),
('How did Darth Vader know what Luke Skywalker got him for Christmas? He felt his presents.', 1),
('What was the mummy''s favorite type of music? Wrap.', 1),
('I''m only familiar with 25 letters of the alphabet. I don''t know why.', 1),
('Did you hear about the beautiful wedding? Even the cake was in tiers.', 1),
('Why are there fences are cemeteries? Because everyone''s always dying to get in.', 1),
('A company is making glass coffins. Whether they''re successful remains to be seen.', 1),
('What did one wall say to the other? "Meet me at the corner!"', 1),
('What do you call a large African mammal with long hair and sandals? A hippie-potamus.', 1),
('How do you think the unthinkable? With an itheberg!', 1),
('What''s the award for being the best dentist? A plaque.', 1),
('Why can''t you hear a pterodactyl go to the bathroom? Because the P is silent.', 1),
('I bought sneakers from a drug dealer. I don''t know what he laced them with but I''ve been tripping all day!', 1),
('Why did Mozart hate chickens? Because when he asked them for their favorite composer, they said, "Bach! Bach! Bach!"', 1),
('Why did the toilet paper roll downhill? To get to the bottom.', 1),
('What''s the best name for a man who can''t stand? Neil.', 1),
('What do you call a deer with no eyes? No eyed deer.', 1),
('Why are groups of fish so smart? Because they travel in schools.', 1),
('How much does the heaviest skeleton weigh? A skeleton.', 1),
('What did the drummer name her twin daughters? Anna One, Anna Two.', 1),
('What''s big, gray and doesn''t matter? An irrelephant.', 1),
('Why did the snowman pick through a bag of carrots? Because he was picking his nose.', 1),
('Why does Waldo only wear stripes? Because he doesn''t want to be spotted.', 1),
('I witnessed an attempted murder earlier—fortunately only one crow showed up!', 1),
('I tried buying camouflage the other day but I couldn''t find any.', 1),
('What did one bean say to the other? "How you bean?"', 1),
('How do you catch a bra? With a booby trap.', 1),
('How many tickles can an octopus take? Tentacles!', 1),
('What do clouds wear under their shorts? Thunderpants.', 1),
('Did you hear about the guy who won the award for best knock knock joke? He won the no bell prize.', 1),
('Why did Cinderella get kicked off of the soccer team? Because she kept running from the ball!', 1),
('How many ears do space aliens have? Three: The left ear, right ear and the final front ear.', 1),
('Cosmetic surgery used to be taboo, but now when you talk about Botox no one raises an eyebrow.', 1),
('Did you hear the one about the three watering holes in the ground? Well, well, well...', 1),
('What did the socks say to the pants? "''Sup britches?!"', 1),
('What shivers at the bottom of the ocean? A nervous wreck.', 1),
('What''s a ninja''s favorite type of shoes? Sneakers!', 1),
('I have the world''s worst thesaurus. Not only is it terrible, it''s also terrible.', 1),
('What do hillbillies drink from? Hiccups.', 1),
('What''s even better than Ted Danson? Ted singing and Danson.', 1),
('Why did the invisible man turn down a job offer? He couldn''t see himself doing it.', 1),
('What kind of music do windmills like? They''re metal fans.', 1),
('What do you call a fish with two knees? A tunee fish.', 1),
('I''d tell you the joke about perforated paper, but it''s tear-able.', 1),
('What do you call someone else''s cheese? Nacho cheese!', 1),
('What do you call a canine magician? A labracadabrador.', 1),
('The rotation of the earth really makes my day.', 1),
('Why do seagulls fly over the sea? Because if they flew over the bay, they''d be called bagels.', 1),
('What did the animals tell Simba when he walked too slow? Mufasa!', 1),
('What do you call Samsung''s security team? The Guardians of the Galaxy!', 1),
('I sold my vacuum yesterday. It was just collecting dust.', 1),
('What kind of tea is the hardest to swallow? Reality.', 1),
('Why did the golfer need new pants? Because he got a hole in one.', 1),
('Why did the man get fired from the calendar factory? Because he took a few days off.', 1),
('What do you call an alligator wearing a vest? An investigator.', 1),
('How do snails fight? They slug it out.', 1),
('What''s Forrest Gump''s email password? 1forrest1.', 1),
('What did the left butt cheek say to the right butt cheek? "You crack me up!"', 1),
('What do you call someone who points out the obvious? Someone who points out the obvious.', 1),
('What sound does a nut make when it sneezes? Cashew!', 1),
('Did you hear about the satellites'' wedding? The ceremony was OK, but the reception was terrific.', 1),
('What did the Atlantic Ocean say to the Pacific Ocean? Nothing, it just waved.', 1),
('What did the fish say when it swam into the wall? "Dam!"', 1),
('Which school supply is king? The ruler.', 1),
('What do you get when you cross a vampire with a snowman? Frostbite.', 1),
('What do you call a person with no body and no nose? Nobody knows.', 1),
('What''s green and sings? Elvis Parsley.', 1),
('How do you make holy water? You boil the hell out of it.', 1),
('A jumper cable walks into a bar. The bartender says, "I''ll serve you, but don''t start anything."', 1),
('What''s the worst part of being an egg? You only get laid once (and it''s with your mom)!', 1),
('Three fish are in a tank. One asked the others, "How the heck do you drive this thing?"', 1),
('What concert is worth just 45 cents? 50 Cent and Nickelback.', 1),
('Why can''t a hand be 12 inches long? Because then it''d be a foot.', 1),
('What''s the difference between a dapper man on a bicycle and a poorly dressed man on a unicycle? Attire!', 1),
('I left my job at a shoe disposal plant. It was sole destroying.', 1),
('The past, the present and the future walked into a bar. It was tense.', 1),
('What did Eminem say when 50 Cent made him a sweater? "Gee, you knit?"', 1),
('What did the thumb say to the finger? "I''m in glove with you."', 1),
('What does a nosy pepper do? It gets jalapeno business!', 1),
('Parallel lines have so much in common. It''s a shame they''ll never meet.', 1),
('There are three types of people in this world: People who are good at math and people who are not.', 1),
('What do you call an Italian astronaut? A specimen.', 1),
('Two guys walk into a bar. The third guy ducks.', 1),
('Why do ghosts love elevators? Because they lift their spirits.', 1),
('What do you call a snobby criminal going downstairs? A condescending con descending.', 1),
('What did the princess say in the photo booth? "Someday my prints will come."', 1),
('What can you do if you''re scared of elevators? Take steps to avoid them.', 1),
('What''s brass and sounds like Tom Jones? Trombones.', 1),
('How do prisoners communicate with one another? Cell phones.', 1),
('How many bugs do you need to rent out an apartment? Tenants.', 1),
('What did one elevator say to the other? "I think I''m coming down with something."', 1),
('What''s a foot''s favorite snack? Dori-toes.', 1),
('The shovel was a truly groundbreaking invention.', 1),
('What did Sushi A say to Sushi B? "Wasa-B!"', 1),
('You know why they called it "the dark ages?" There were too many knights.', 1),
('What''s the loudest kind of pet you can get? A trumpet.', 1),
('Two cannibals are eating a clown. One asks the other, "Does this taste funny to you?"', 1),
('Does anyone need an ark? I Noah guy.', 1),
('Why did the picture go to jail? Because it was framed!', 1),
('Why did the melons have a big wedding? Because they cantaloupe.', 1),
('Have you heard the joke about the bed? No? That''s because it hasn''t been made yet.', 1),
('Why can''t wildcats take tests? There are too many cheetahs.', 1),
('What do you call a can opener that doesn''t work? A can''t opener.', 1),
('Why shouldn''t you make a "dad joke" if you''re not a dad? Because it''s a faux pa.', 1),
('A man died after drinking varnish. It was a terrible end, but a beautiful finish.', 1),
('What''s the difference between Prince William and a tennis ball? One is heir to the throne and one is thrown in the air.', 1),
('What''s the derivative of Amazon? Amazon Prime.', 1),
('Why couldn''t the pirate sit down? His booty got stolen!', 1),
('Why was the broom late for a meeting? It overswept.', 1),
('How did the hipster burn his mouth? He sipped his coffee before it was cool.', 1),
('What did the over-excited gardener do when spring came? She wet her plants.', 1),
('What do you call Batman if he skips church? Christian Bale!', 1),
('I used to hate body hair, but then it grew on me.', 1),
('What do you call a bear with no teeth? A gummy bear.', 1),
('What kind of dinosaur has the biggest vocabulary? The thesaurus!', 1),
('What did the grape do when it got stomped on? It let out a little wine.', 1),
('What''s the best part about Switzerland? The flag is a big plus.', 1),
('What did the buffalo say when his son left? Bison!', 1),
('What do you call a fake noodle? An impasta!', 1),
('Did you know the first French fries weren''t cooked in France? They were cooked in Greece!', 1),
('What do carb-loving zombies eat? Graaaaaaaains.', 1),
('What''s the best time to see a dentist? Tooth hurty.', 1),
('What''s the difference between a hippo and a Zippo? One is heavy and one is a lot lighter.', 1),
('Why shouldn''t you write with a dull pencil? Because it''s pointless.', 1),
('How much does an influencer weigh? An Instagram.', 1),
('What do you get when you combine a rhetorical question and a joke?', 1);