# Этап сборки
FROM node:18 AS builder

WORKDIR /app

COPY package.json ./
COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

RUN npm install

RUN echo "VITE_API_URL=${VITE_API_URL}"

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
