version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    depends_on:
      - db
    environment:
      ENV: prod
      DB_DRIVER: postgres
      DB_CONNECTION_STRING: "host=db user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"
      HTTP_SERVER_ADDRESS: "0.0.0.0:9999"
      HTTP_SERVER_TIMEOUT: "4s"
      HTTP_SERVER_IDLE_TIMEOUT: "60s"
      JWT_SECRET: "${JWT_SECRET_KEY}"
    ports:
      - "127.0.0.1:9999:9999"

  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:8080:80"

volumes:
  db_data: 